---
- name: Build Docker Image
  hosts: localhost
  tasks:
    - name: Build Docker Image
      docker_image:
        name: image1
        build:  
          path: /home/ubuntu/abc/
        source: build
        state: present
